name: "Generate top index html"

on:
  push:
    branches:
      - master
      - stable*

jobs:
  build:
    name: Generate top index for documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Github Pages branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Get stable branches
      id: branch
      run: |
        branches=$(git branch -r | grep -E 'origin/stable[0-9]+' | sed 's/.*stable//' | sort -n -r | tr '\n' ' ')
        echo "branches=$branches" >> $GITHUB_OUTPUT

    - name: Setup php
      uses: shivammathur/setup-php@27853eb8b46dc01c33bf9fef67d98df2683c3be2 # v2.34.0

    - name: Generate index.html
      run: |
        php build/build-index.php ${{ steps.branch.outputs.branches }}
        mv build/index.html /tmp/index.html
        mv build/static/ /tmp/static/

    - name: Switch to gh-pages branch
      run: |
        git checkout gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push changes
      run: |
        # Move the generated index.html and static files to the root of the gh-pages branch
        rm -rf index.html static/
        mv /tmp/index.html index.html
        mv /tmp/static/ static/
        git add index.html static/
        git commit -m "chore: update index.html for documentation" || echo "No changes to commit"
        git push origin gh-pages
