name: "Build documentation"

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manual:
          - name: "user_manual"
            directory: "user_manual"
            make_target: "html"
            build_path: "_build/html"
            
          - name: "user_manual-en"
            directory: "user_manual"
            make_target: "html-lang-en"
            build_path: "_build/html"
            
          - name: "developer_manual"
            directory: "developer_manual"
            make_target: "html"
            build_path: "_build/html/com"
            
          - name: "admin_manual"
            directory: "admin_manual"
            make_target: "html"
            build_path: "_build/html/com"
            
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install pip dependencies
      run: pip install -r requirements.txt

    - name: Build using Makefile
      run: cd ${{ matrix.manual.directory }} && make ${{ matrix.manual.make_target }}

    - name: Pack the results in local tar file
      run: tar czf /tmp/documentation.tar.gz -C ${{ matrix.manual.directory }}/${{ matrix.manual.build_path }} .

    - name: Upload static documentation
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ matrix.manual.name }}
        path: "/tmp/documentation.tar.gz"
