name: "Build documentation"

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        manual:
          - name: "user_manual"
            directory: "user_manual"
            make_target: "html"
            build_path: "_build/html"
            publish: true
            
          - name: "user_manual-en"
            directory: "user_manual"
            make_target: "html-lang-en"
            build_path: "_build/html"
            publish: false
            
          - name: "developer_manual"
            directory: "developer_manual"
            make_target: "html"
            build_path: "_build/html/com"
            publish: true
            
          - name: "admin_manual"
            directory: "admin_manual"
            make_target: "html"
            build_path: "_build/html/com"
            publish: true
            
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install pip dependencies
      run: pip install -r requirements.txt

    - name: Build using Makefile
      run: cd ${{ matrix.manual.directory }} && make ${{ matrix.manual.make_target }}

    - name: Upload static documentation
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ matrix.manual.name }}
        path: ${{ matrix.manual.directory }}/${{ matrix.manual.build_path }}

    - name: Upload static documentation as Github Pages
      if: ${{ matrix.manual.publish }}
      id: deployment
      uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        name: ${{ matrix.manual.name }}
        path: ${{ matrix.manual.directory }}/${{ matrix.manual.build_path }}
