name: Checkout File from Master

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file to checkout from master'
        required: true
        type: string
        default: .github/workflows/sphinxbuild.yml
      target_branch:
        description: 'Target branch to commit the file to'
        required: true
        type: string
        default: stable20

jobs:
  checkout-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to access all branches
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ inputs.target_branch }}
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Checkout file from master
      run: |
        echo "Checking out file: ${{ inputs.file_path }} from master branch"
        git checkout origin/master -- ${{ inputs.file_path }}
    
    - name: Commit and push changes
      run: |
        git add ${{ inputs.file_path }}
        git commit -sm "chore: update ${{ inputs.file_path }} from master branch"
        
        git push origin ${{ inputs.target_branch }}
